# Generated by Django 5.2.5 on 2025-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='JT Sistemas', max_length=200)),
                ('logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapp_token', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_webhook_verify_token', models.CharField(blank=True, max_length=200, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
                'db_table': 'configuracao_empresa',
            },
        ),
    ]
