# Generated by Django 5.2.5 on 2025-08-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
    ]
